language: php

php: [5.4, 5.5, hhvm]

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: bin/phpspec run -fpretty -v
